//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int id { get; set; }
        public Nullable<int> idApplication { get; set; }
        public string Permission { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
    
        public virtual Permission Permission1 { get; set; }
        public virtual AccessApplication AccessApplication { get; set; }
    }
}
